-- remove everything
drop table starb;
drop table enrol;
drop table teacher;
drop table course;
drop table weekplan;
drop table plan;
drop table starb;
drop table starbkey;
drop table tickets;
drop table tickets_trace;
drop table show;
drop table room;
drop table members;
drop table groups;
drop table users;
drop table periode;
drop table calendar;
drop table subject;
