drop table quiz;
drop table quiz_container;
drop table quiz_useranswer;
drop table quiz_qtag;
drop table quiz_question;
drop table quiz_tag;

CREATE TABLE quiz_tag (
    id SERIAL primary key,
    tagname varchar(36) not null
);

CREATE TABLE quiz_question (
    id SERIAL primary key,
    name varchar(64) not null,
    points  smallint default 1,
    qtype varchar(32) not null default 'multiple',
    qtext varchar,
    teachid int references users on delete set null,
    created  int not null,
    modified  int not null,
    parent int default 0    -- if this question is a copy - id of source
);
CREATE INDEX question_qtype ON quiz_question (qtype);
CREATE INDEX question_teachid ON quiz_question (teachid);

CREATE TABLE quiz_qtag (
    tid int references quiz_tag on delete set null,  
    qid int references quiz_question on delete set null 
);
CREATE INDEX qtag_tq ON quiz_qtag (tid,qid);

-- CREATE INDEX user_institution ON users (institution);
-- CREATE INDEX user_department ON users (department);

CREATE TABLE quiz_useranswer (
    id SERIAL primary key,
    qid int references quiz_question on delete set null,
    userid int references users on delete set null,
    response varchar,
    score smallint default 0,
    attemptnum smallint default 0,
    teachcomment varchar,
    usercomment varchar,
    certanty smallint default 0,
    time int,
    param varchar,   -- used by dynamically generated questions
    instance int default 0   -- for dynamic questions ( text generated by sympy etc) 
    -- we may have more than one instance of a given question on the page
);


CREATE TABLE quiz_container (
    id SERIAL primary key,
    cid int references quiz_question on delete set null,  -- the question containing this question
    qid int references quiz_question on delete set null  -- the contained question
);

CREATE TABLE quiz (
    id SERIAL primary key,
    name varchar(64) not null,
    julday  int not null,
    time int,
    teachid int references users on delete set null,
    cid int references quiz_question on delete set null
);
