drop table quiz_container;
drop table question_container;
drop table quiz_useranswer;
drop table quiz;
drop table quiz_qtag;
drop table quiz_question;
drop table quiz_tag;

CREATE TABLE quiz_tag (
    id SERIAL primary key,
    tagname varchar(36) not null
);

CREATE TABLE quiz_question (
    id SERIAL primary key,
    name varchar(64) default '',
    points  smallint default 1,
    qtype varchar(32) not null default 'multiple',
    qtext varchar default '',
    qfasit varchar default '',   -- only ever sent if a teacher is editing a question
    -- otherwise NOT SENT FROM SERVER
    teachid int references users on delete set null,
    created  bigint not null,
    modified  bigint not null,
    parent int default 0    -- if this question is a copy - id of source
);
CREATE INDEX question_qtype ON quiz_question (qtype);
CREATE INDEX question_teachid ON quiz_question (teachid);

CREATE TABLE quiz_qtag (
    tid int references quiz_tag on delete cascade,  
    qid int references quiz_question on delete cascade 
);
CREATE INDEX qtag_tq ON quiz_qtag (tid,qid);

-- CREATE INDEX user_institution ON users (institution);
-- CREATE INDEX user_department ON users (department);



CREATE TABLE quiz (
    id SERIAL primary key,
    name varchar(64) not null,
    julday  int default 0,
    time int default 0,
    teachid int references users on delete set null,
    cid int references quiz_question on delete set null,
    courseid int references course on delete set null,
    -- a course may have a quiz with the same name as the course
    -- such a quiz is used as a workbook
    UNIQUE (courseid,name)
    -- each quizname must be unique within a course
);

CREATE TABLE quiz_useranswer (
    id SERIAL primary key,
    qid int references quiz_question on delete cascade,
    qzid int references quiz on delete set null,
    userid int references users on delete set null,
    response varchar,
    score smallint default 0,
    attemptnum smallint default 0,
    teachcomment varchar,
    usercomment varchar,
    certanty smallint default 0,
    time bigint,
    param varchar,   -- used by dynamically generated questions
    instance int default 0   -- for dynamic questions ( text generated by sympy etc) 
    -- we may have more than one instance of a given question on the page
);
CREATE INDEX quiz_ua_qid ON quiz_useranswer (qid);
CREATE INDEX quiz_ua_qzid ON quiz_useranswer (qzid);
CREATE INDEX quiz_ua_uid ON quiz_useranswer (userid);
CREATE INDEX quiz_ua_qu ON quiz_useranswer (userid,qid);

CREATE TABLE quiz_container (
    id SERIAL primary key,
    cid int references quiz_question on delete cascade,  -- the question containing this quiz
    qizid int references quiz on delete cascade          -- the contained quiz
);
CREATE INDEX qzcontainer ON quiz_container (cid,qizid);

CREATE TABLE question_container (
    id SERIAL primary key,
    cid int references quiz_question on delete cascade ,  -- the question containing this question
    qid int references quiz_question on delete cascade    -- the contained question
);
CREATE INDEX qncontainer ON question_container (cid,qid);
